#define NOT ! 
#define AND && 
#define OR || 

OK   IorD = S0 

RegWrite = (NOT(S3 AND S2 AND NOT(S1 AND NOT(S0) OR (NOT(S3 AND S2 AND S1 AND S0) OR (S3 AND NOT(S2 AND S1 AND S0) OR (S3 AND S2 AND NOT(S1 AND S0)

MemRead = (NOT(S3 AND NOT(S2 AND NOT(S1 AND NOT(S0) OR (NOT(S3 AND NOT(S2 AND S1 AND S0)

MemWrite = NOT(S3 AND S2 AND NOT(S1 AND S0

MemToReg_0 = NOT(S3 AND NOT(S1

MemToReg_1 = S3 AND S2

IRWrite = NOT(S3) AND NOT(S2) AND NOT(S1) AND NOT(S0)

PCSource_0 = S1 OR (S3 AND NOT(S0))

PCSource_1 = S0

ALUOp_0 = S3

ALUOp_1 = (NOT(S3) AND S2) OR (S3 AND S1)

ALUSrcB_0 = NOT(S3) AND NOT(S1)

ALUSrcB_1 = SO OR (NOT(S2) AND S1)

ALUSrcA = S1 OR S3

RegDst_0 = NOT(S3)

RegDst_1 = NOT(S1)

PCWrite = (S3 AND NOT(S1)) OR (NOT(S2) AND NOT(S1) AND NOT(S0)) OR (S3 AND S2 AND S0)

PCWriteCond = S3 AND NOT(S1) AND NOT(S0)

BNE = S2

//---------------------------------------------------------------------------------------------------------------------------------------------

NS0 = (NOT(S3) AND NOT(S2) AND NOT(S1) AND NOT(S0)) OR (NOT(S3) AND S2 AND S1 AND NOT(S0)) OR (S3 AND NOT(S2) AND S1 AND NOT(S0)) 
	   OR (S3 AND S2 AND S1 AND NOT(S0)) OR (NOT(S3) AND NOT(S2) AND NOT(S1) AND S0 AND NOT(OP5) AND NOT(OP4) AND NOT(OP3) AND NOT(OP2) AND OP1 AND NOT(OP0))
	   OR (NOT(S3) AND NOT(S2) AND NOT(S1) AND S0 AND NOT(OP5) AND NOT(OP4) AND NOT(OP3) AND NOT(OP2) AND OP1 AND OP0) 
	   OR (NOT(S3) AND NOT(S2) AND NOT(S1) AND SO AND NOT(OP5) AND OP4 AND NOT(OP3) AND OP2 AND NOT(OP1) AND NOT(OP0)) 
	   OR (NOT(S3) AND NOT(S2) AND S1 AND NOT(S0) AND OP5 AND NOT(OP4) AND NOT(OP3) AND NOT(OP2) AND OP1 AND OP0) 
	   OR (NOT(S3) AND NOT(S2) AND S1 AND NOT(SO) AND OP5 AND NOT(OP4) AND OP3 AND NOT(OP2) AND OP1 AND OP0)
	   OR (NOT(S3) AND NOT(S2) AND S1 AND NOT(S0) AND NOT(OP5) AND NOT(OP4) AND OP3 AND NOT(OP2) AND NOT(OP1) AND NOT(OP0))

NS1 = (NOT(S3) AND NOT(S2) AND NOT(S1) AND S0 AND ( (OP5 AND NOT(OP4) AND NOT(OP3) AND NOT(OP2) AND OP1 AND OP0) OR (OP5 AND NOT(OP4) AND OP3 AND NOT(OP2) AND OP1 AND OP0) OR (NOT(OP5) AND NOT(OP4) AND OP3 AND NOT(OP2) AND NOT(OP1) AND NOT(OP0)) ) )
	   OR (NOT(S3) AND NOT(S2) AND S1 AND NOT(S0) AND OP5 AND NOT(OP4) AND NOT(OP3) AND NOT(OP2) AND OP1 AND OP0)
	   OR (NOT(S3) AND NOT(S2) AND NOT(S1) AND SO AND NOT(OP5) AND NOT(OP4) AND NOT(OP3) AND NOT(OP2) AND NOT(OP1) AND NOT(OP0))
	   OR (NOT(S3) AND S2 AND S1 AND NOT(S0))
	   OR (NOT(S3) AND NOT(S2) AND NOT(S1) AND S0 AND NOT(OP5) AND NOT(OP4) AND OP3 AND OP2 AND NOT(OP1) AND NOT(OP0))
	   OR (S3 AND NOT(S2) AND S1 AND NOT(S0))
	   OR (NOT(S3) AND NOT(S2) AND NOT(S1) AND S0 AND NOT(OP5) AND OP4 AND NOT(OP3) AND OP2 AND NOT(OP1) AND OP0)
	   OR (S3 AND S2 AND S1 AND NOT(S0))

NS2 = 